// @generated
// This file is @generated by prost-build.
/// Only committed writes relevant to Tessera; transactions with no matches are omitted.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockStorageChanges {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<TransactionStorageChanges>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionStorageChanges {
    #[prost(message, optional, tag="1")]
    pub tx: ::core::option::Option<::tycho_substreams::prelude::Transaction>,
    /// Sorted by execution ordinal, including repeated writes and clears.
    #[prost(message, repeated, tag="2")]
    pub writes: ::prost::alloc::vec::Vec<StorageChange>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorageChange {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub old_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub new_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="5")]
    pub ordinal: u64,
}
// @@protoc_insertion_point(module)
