// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pool {
    /// The bytes32 PoolId, keccak256 of the 6-word PoolKey (infinity-core src/types/PoolId.sol:10-15).
    #[prost(bytes="vec", tag="1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub currency0: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub currency1: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub created_tx_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="4")]
    pub index: u64,
}
/// Absolute reserves of one bin, before and after a transaction touched it.
///
/// Unlike CL ticks, these are NOT deltas. The events do not carry per-bin amounts, so the values
/// are read out of the BinPoolManager storage diff (see 5_map_bin_changes.rs). Both sides are kept
/// because map_protocol_changes needs `old` to decide Creation vs Update vs Deletion, and
/// map_balance_changes needs `new - old` to derive the token balance delta.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BinDelta {
    /// The raw 32-byte pool id.
    #[prost(bytes="vec", tag="1")]
    pub pool_id: ::prost::alloc::vec::Vec<u8>,
    /// Liquidity Book bin id, uint24 on chain (0 .. 2^24-1), widened here.
    #[prost(uint32, tag="2")]
    pub bin_id: u32,
    /// Packed reserves BEFORE the write: [0,128) reserveX | [128,256) reserveY, big endian bytes32.
    /// All zero when the bin did not exist (PackedUint128Math.sol).
    #[prost(bytes="vec", tag="3")]
    pub old_packed: ::prost::alloc::vec::Vec<u8>,
    /// Packed reserves AFTER the write, same encoding. All zero when the bin was emptied.
    #[prost(bytes="vec", tag="4")]
    pub new_packed: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="5")]
    pub ordinal: u64,
    #[prost(message, optional, tag="6")]
    pub transaction: ::core::option::Option<Transaction>,
    /// Carried through so map_balance_changes needs no second lookup: a BinDelta knows its pool but
    /// the pool's tokens only exist on the event it came from.
    #[prost(bytes="vec", tag="7")]
    pub currency0: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub currency1: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BinDeltas {
    #[prost(message, repeated, tag="1")]
    pub deltas: ::prost::alloc::vec::Vec<BinDelta>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="3")]
    pub pool_events: ::prost::alloc::vec::Vec<events::PoolEvent>,
}
/// Nested message and enum types in `Events`.
pub mod events {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PoolEvent {
        #[prost(uint64, tag="100")]
        pub log_ordinal: u64,
        /// 0x-prefixed hex of the bytes32 pool id; also the Tycho component id.
        #[prost(string, tag="102")]
        pub pool_id: ::prost::alloc::string::String,
        #[prost(string, tag="103")]
        pub currency0: ::prost::alloc::string::String,
        #[prost(string, tag="104")]
        pub currency1: ::prost::alloc::string::String,
        #[prost(message, optional, tag="105")]
        pub transaction: ::core::option::Option<super::Transaction>,
        #[prost(oneof="pool_event::Type", tags="1, 2, 3, 4, 5, 6")]
        pub r#type: ::core::option::Option<pool_event::Type>,
    }
    /// Nested message and enum types in `PoolEvent`.
    pub mod pool_event {
        #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Initialize {
            /// PoolKey.fee: LP fee in pips, or 0x800000 for a dynamic fee (LPFeeLibrary.sol:19).
            #[prost(uint32, tag="1")]
            pub fee: u32,
            /// Decoded from parameters bits [16, 32) (BinPoolParametersHelper.sol).
            #[prost(uint32, tag="2")]
            pub bin_step: u32,
            /// The bin the pool starts at. uint24 on chain.
            #[prost(uint32, tag="3")]
            pub active_id: u32,
            #[prost(string, tag="4")]
            pub hooks: ::prost::alloc::string::String,
            /// Raw PoolKey.parameters (hook bitmap in bits [0, 16)).
            #[prost(bytes="vec", tag="5")]
            pub parameters: ::prost::alloc::vec::Vec<u8>,
        }
        /// Mint and Burn carry the bin ids they touched but not the resulting reserves, so
        /// 5_map_bin_changes.rs uses `ids` only to decide which storage slots to look up.
        #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Mint {
            #[prost(string, tag="1")]
            pub sender: ::prost::alloc::string::String,
            #[prost(uint32, repeated, tag="2")]
            pub ids: ::prost::alloc::vec::Vec<u32>,
            #[prost(string, tag="3")]
            pub salt: ::prost::alloc::string::String,
        }
        #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Burn {
            #[prost(string, tag="1")]
            pub sender: ::prost::alloc::string::String,
            #[prost(uint32, repeated, tag="2")]
            pub ids: ::prost::alloc::vec::Vec<u32>,
            #[prost(string, tag="3")]
            pub salt: ::prost::alloc::string::String,
        }
        #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Swap {
            #[prost(string, tag="1")]
            pub sender: ::prost::alloc::string::String,
            /// Signed int128 as decimal string, from the pool's point of view.
            #[prost(string, tag="2")]
            pub amount0: ::prost::alloc::string::String,
            #[prost(string, tag="3")]
            pub amount1: ::prost::alloc::string::String,
            /// The active bin AFTER the swap. Combined with the pre-swap value from store_active_id
            /// this gives the inclusive range of bins the swap crossed.
            #[prost(uint32, tag="4")]
            pub active_id: u32,
            /// Composite swap fee actually charged (protocol + LP), pips.
            #[prost(uint32, tag="5")]
            pub fee: u32,
        }
        #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Donate {
            #[prost(string, tag="1")]
            pub sender: ::prost::alloc::string::String,
            #[prost(string, tag="2")]
            pub amount0: ::prost::alloc::string::String,
            #[prost(string, tag="3")]
            pub amount1: ::prost::alloc::string::String,
            #[prost(uint32, tag="4")]
            pub bin_id: u32,
        }
        #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
        pub struct ProtocolFeeUpdated {
            #[prost(string, tag="1")]
            pub pool_id: ::prost::alloc::string::String,
            /// uint24: bits [0,12) zero-for-one, bits [12,24) one-for-zero (ProtocolFeeLibrary.sol:22-31).
            #[prost(uint32, tag="2")]
            pub protocol_fee: u32,
        }
        #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
        pub enum Type {
            #[prost(message, tag="1")]
            Initialize(Initialize),
            #[prost(message, tag="2")]
            Mint(Mint),
            #[prost(message, tag="3")]
            Burn(Burn),
            #[prost(message, tag="4")]
            Swap(Swap),
            #[prost(message, tag="5")]
            Donate(Donate),
            #[prost(message, tag="6")]
            ProtocolFeeUpdated(ProtocolFeeUpdated),
        }
    }
}
// @@protoc_insertion_point(module)
