// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pool {
    /// The bytes32 PoolId, keccak256 of the 6-word PoolKey (infinity-core src/types/PoolId.sol:10-15).
    #[prost(bytes="vec", tag="1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub currency0: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub currency1: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub created_tx_hash: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="4")]
    pub index: u64,
}
/// A change to a pool's tick net liquidity.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TickDelta {
    /// The raw 32-byte pool id.
    #[prost(bytes="vec", tag="1")]
    pub pool_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag="2")]
    pub tick_index: i32,
    /// Bigint encoded as signed big endian bytes.
    #[prost(bytes="vec", tag="3")]
    pub liquidity_net_delta: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="4")]
    pub ordinal: u64,
    #[prost(message, optional, tag="5")]
    pub transaction: ::core::option::Option<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TickDeltas {
    #[prost(message, repeated, tag="1")]
    pub deltas: ::prost::alloc::vec::Vec<TickDelta>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiquidityChange {
    #[prost(bytes="vec", tag="1")]
    pub pool_address: ::prost::alloc::vec::Vec<u8>,
    /// Bigint encoded as signed big endian bytes.
    #[prost(bytes="vec", tag="2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration="LiquidityChangeType", tag="3")]
    pub change_type: i32,
    #[prost(uint64, tag="4")]
    pub ordinal: u64,
    #[prost(message, optional, tag="5")]
    pub transaction: ::core::option::Option<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiquidityChanges {
    #[prost(message, repeated, tag="1")]
    pub changes: ::prost::alloc::vec::Vec<LiquidityChange>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="3")]
    pub pool_events: ::prost::alloc::vec::Vec<events::PoolEvent>,
}
/// Nested message and enum types in `Events`.
pub mod events {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PoolEvent {
        #[prost(uint64, tag="100")]
        pub log_ordinal: u64,
        /// 0x-prefixed hex of the bytes32 pool id; also the Tycho component id.
        #[prost(string, tag="102")]
        pub pool_id: ::prost::alloc::string::String,
        #[prost(string, tag="103")]
        pub currency0: ::prost::alloc::string::String,
        #[prost(string, tag="104")]
        pub currency1: ::prost::alloc::string::String,
        #[prost(message, optional, tag="105")]
        pub transaction: ::core::option::Option<super::Transaction>,
        #[prost(oneof="pool_event::Type", tags="1, 2, 3, 4, 5")]
        pub r#type: ::core::option::Option<pool_event::Type>,
    }
    /// Nested message and enum types in `PoolEvent`.
    pub mod pool_event {
        #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Initialize {
            #[prost(string, tag="1")]
            pub sqrt_price_x96: ::prost::alloc::string::String,
            #[prost(int32, tag="2")]
            pub tick: i32,
            /// PoolKey.fee: LP fee in pips, or 0x800000 for a dynamic fee (LPFeeLibrary.sol:19).
            #[prost(uint32, tag="3")]
            pub fee: u32,
            /// Decoded from parameters bits [16, 40) (CLPoolParametersHelper.sol:19-32).
            #[prost(int32, tag="4")]
            pub tick_spacing: i32,
            #[prost(string, tag="5")]
            pub hooks: ::prost::alloc::string::String,
            /// Raw PoolKey.parameters (hook bitmap in bits [0, 16)).
            #[prost(bytes="vec", tag="6")]
            pub parameters: ::prost::alloc::vec::Vec<u8>,
        }
        #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
        pub struct ModifyLiquidity {
            #[prost(string, tag="1")]
            pub sender: ::prost::alloc::string::String,
            #[prost(int32, tag="2")]
            pub tick_lower: i32,
            #[prost(int32, tag="3")]
            pub tick_upper: i32,
            /// Signed int256 as decimal string.
            #[prost(string, tag="4")]
            pub liquidity_delta: ::prost::alloc::string::String,
            #[prost(string, tag="5")]
            pub salt: ::prost::alloc::string::String,
        }
        #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Swap {
            #[prost(string, tag="1")]
            pub sender: ::prost::alloc::string::String,
            /// Signed int128 as decimal string.
            #[prost(string, tag="2")]
            pub amount0: ::prost::alloc::string::String,
            #[prost(string, tag="3")]
            pub amount1: ::prost::alloc::string::String,
            #[prost(string, tag="4")]
            pub sqrt_price_x96: ::prost::alloc::string::String,
            #[prost(string, tag="5")]
            pub liquidity: ::prost::alloc::string::String,
            #[prost(int32, tag="6")]
            pub tick: i32,
            /// Composite swap fee actually charged (protocol + LP), pips.
            #[prost(uint32, tag="7")]
            pub fee: u32,
        }
        #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Donate {
            #[prost(string, tag="1")]
            pub sender: ::prost::alloc::string::String,
            #[prost(string, tag="2")]
            pub amount0: ::prost::alloc::string::String,
            #[prost(string, tag="3")]
            pub amount1: ::prost::alloc::string::String,
        }
        #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
        pub struct ProtocolFeeUpdated {
            #[prost(string, tag="1")]
            pub pool_id: ::prost::alloc::string::String,
            /// uint24: bits [0,12) zero-for-one, bits [12,24) one-for-zero (ProtocolFeeLibrary.sol:22-31).
            #[prost(uint32, tag="2")]
            pub protocol_fee: u32,
        }
        #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
        pub enum Type {
            #[prost(message, tag="1")]
            Initialize(Initialize),
            #[prost(message, tag="2")]
            ModifyLiquidity(ModifyLiquidity),
            #[prost(message, tag="3")]
            Swap(Swap),
            #[prost(message, tag="4")]
            Donate(Donate),
            #[prost(message, tag="5")]
            ProtocolFeeUpdated(ProtocolFeeUpdated),
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LiquidityChangeType {
    Delta = 0,
    Absolute = 1,
}
impl LiquidityChangeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            LiquidityChangeType::Delta => "DELTA",
            LiquidityChangeType::Absolute => "ABSOLUTE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DELTA" => Some(Self::Delta),
            "ABSOLUTE" => Some(Self::Absolute),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
