// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Pool {
    #[prost(bytes="vec", tag="1")]
    pub token0: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub token1: ::prost::alloc::vec::Vec<u8>,
}
/// A change to a pool's tick.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TickDelta {
    /// The address of the pool.
    #[prost(bytes="vec", tag="1")]
    pub pool_address: ::prost::alloc::vec::Vec<u8>,
    /// The index of the tick.
    #[prost(int32, tag="2")]
    pub tick_index: i32,
    /// The liquidity net delta of this tick. Bigint encoded as signed big endian bytes.
    #[prost(bytes="vec", tag="3")]
    pub liquidity_net_delta: ::prost::alloc::vec::Vec<u8>,
    /// Used to determine the order of the balance changes. Necessary for the balance store.
    #[prost(uint64, tag="4")]
    pub ordinal: u64,
    #[prost(message, optional, tag="5")]
    pub transaction: ::core::option::Option<::tycho_substreams::prelude::Transaction>,
}
/// A group of TickDelta
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TickDeltas {
    #[prost(message, repeated, tag="1")]
    pub deltas: ::prost::alloc::vec::Vec<TickDelta>,
}
/// A change to a pool's liquidity.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LiquidityChange {
    /// The address of the pool.
    #[prost(bytes="vec", tag="1")]
    pub pool_address: ::prost::alloc::vec::Vec<u8>,
    /// The liquidity changed amount. Bigint encoded as signed big endian bytes.
    #[prost(bytes="vec", tag="2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    /// The type of update, can be absolute or delta.
    #[prost(enumeration="LiquidityChangeType", tag="3")]
    pub change_type: i32,
    /// Used to determine the order of the balance changes. Necessary for the balance store.
    #[prost(uint64, tag="4")]
    pub ordinal: u64,
    #[prost(message, optional, tag="5")]
    pub transaction: ::core::option::Option<::tycho_substreams::prelude::Transaction>,
}
/// A group of LiquidityChange
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiquidityChanges {
    #[prost(message, repeated, tag="1")]
    pub changes: ::prost::alloc::vec::Vec<LiquidityChange>,
}
/// All numeric amounts below are BigInt values encoded as signed big-endian bytes.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub pool_events: ::prost::alloc::vec::Vec<events::PoolEvent>,
}
/// Nested message and enum types in `Events`.
pub mod events {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct PoolEvent {
        #[prost(uint64, tag="9")]
        pub log_ordinal: u64,
        #[prost(bytes="vec", tag="10")]
        pub pool_address: ::prost::alloc::vec::Vec<u8>,
        #[prost(bytes="vec", tag="11")]
        pub token0: ::prost::alloc::vec::Vec<u8>,
        #[prost(bytes="vec", tag="12")]
        pub token1: ::prost::alloc::vec::Vec<u8>,
        #[prost(message, optional, tag="13")]
        pub transaction: ::core::option::Option<::tycho_substreams::prelude::Transaction>,
        #[prost(oneof="pool_event::Typ", tags="1, 2, 3, 4, 5, 6, 7, 8")]
        pub typ: ::core::option::Option<pool_event::Typ>,
    }
    /// Nested message and enum types in `PoolEvent`.
    pub mod pool_event {
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Initialize {
            #[prost(bytes="vec", tag="1")]
            pub sqrt_price: ::prost::alloc::vec::Vec<u8>,
            #[prost(int32, tag="2")]
            pub tick: i32,
        }
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Mint {
            #[prost(int32, tag="1")]
            pub tick_lower: i32,
            #[prost(int32, tag="2")]
            pub tick_upper: i32,
            #[prost(bytes="vec", tag="3")]
            pub amount: ::prost::alloc::vec::Vec<u8>,
            #[prost(bytes="vec", tag="4")]
            pub amount_0: ::prost::alloc::vec::Vec<u8>,
            #[prost(bytes="vec", tag="5")]
            pub amount_1: ::prost::alloc::vec::Vec<u8>,
        }
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Collect {
            #[prost(bytes="vec", tag="1")]
            pub amount_0: ::prost::alloc::vec::Vec<u8>,
            #[prost(bytes="vec", tag="2")]
            pub amount_1: ::prost::alloc::vec::Vec<u8>,
        }
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Burn {
            #[prost(int32, tag="1")]
            pub tick_lower: i32,
            #[prost(int32, tag="2")]
            pub tick_upper: i32,
            #[prost(bytes="vec", tag="3")]
            pub amount: ::prost::alloc::vec::Vec<u8>,
        }
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Swap {
            #[prost(bytes="vec", tag="1")]
            pub amount_0: ::prost::alloc::vec::Vec<u8>,
            #[prost(bytes="vec", tag="2")]
            pub amount_1: ::prost::alloc::vec::Vec<u8>,
            #[prost(bytes="vec", tag="3")]
            pub sqrt_price: ::prost::alloc::vec::Vec<u8>,
            #[prost(bytes="vec", tag="4")]
            pub liquidity: ::prost::alloc::vec::Vec<u8>,
            #[prost(int32, tag="5")]
            pub tick: i32,
        }
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct Flash {
            #[prost(bytes="vec", tag="1")]
            pub paid_0: ::prost::alloc::vec::Vec<u8>,
            #[prost(bytes="vec", tag="2")]
            pub paid_1: ::prost::alloc::vec::Vec<u8>,
        }
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct CollectProtocol {
            #[prost(bytes="vec", tag="1")]
            pub amount_0: ::prost::alloc::vec::Vec<u8>,
            #[prost(bytes="vec", tag="2")]
            pub amount_1: ::prost::alloc::vec::Vec<u8>,
        }
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
        pub struct FeeAdjustment {
            #[prost(bytes="vec", tag="1")]
            pub new_fee: ::prost::alloc::vec::Vec<u8>,
        }
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
        pub enum Typ {
            #[prost(message, tag="1")]
            Initialize(Initialize),
            #[prost(message, tag="2")]
            Mint(Mint),
            #[prost(message, tag="3")]
            Collect(Collect),
            #[prost(message, tag="4")]
            Burn(Burn),
            #[prost(message, tag="5")]
            Swap(Swap),
            #[prost(message, tag="6")]
            Flash(Flash),
            #[prost(message, tag="7")]
            CollectProtocol(CollectProtocol),
            #[prost(message, tag="8")]
            FeeAdjustment(FeeAdjustment),
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LiquidityChangeType {
    Delta = 0,
    Absolute = 1,
}
impl LiquidityChangeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Delta => "DELTA",
            Self::Absolute => "ABSOLUTE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DELTA" => Some(Self::Delta),
            "ABSOLUTE" => Some(Self::Absolute),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
