INSERT INTO trades (
    id, chain, block_number, block_time, tx_hash, tx_index, call_index,
    tx_success, call_success, router, router_version, strategy, funding,
    eoa, msg_sender, receiver, token_in, token_out, amount_in, min_amount_out,
    native_value, gas_used, n_tokens, n_hops, executors, protocol_systems, wrap_eth, unwrap_eth,
    amount_out
) VALUES
    ('ethereum-input', 'ethereum', 1, now(), '0x01', 0, 0,
     true, true, '0x01', 'v3_1', 'single', 'transfer_from',
     '0x01', '0x01', '0x01', '0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
     '0xdddddddddddddddddddddddddddddddddddddddd', 1000000000000000000, 0,
     0, 1, 0, 1, '{}', '{}', false, false, NULL),
    ('base-output', 'base', 1, now(), '0x02', 0, 0,
     true, true, '0x01', 'v3_1', 'single', 'transfer_from',
     '0x01', '0x01', '0x01', '0xdddddddddddddddddddddddddddddddddddddddd',
     '0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb', 1, 0,
     0, 1, 0, 1, '{}', '{}', false, false, 2000000),
    ('ethereum-native', 'ethereum', 1, now(), '0x03', 0, 0,
     true, true, '0x01', 'v3_1', 'single', 'transfer_from',
     '0x01', '0x01', '0x01', '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
     '0xdddddddddddddddddddddddddddddddddddddddd', 1000000000000000000, 0,
     0, 1, 0, 1, '{}', '{}', false, false, NULL),
    ('failed-call', 'ethereum', 1, now(), '0x05', 0, 0,
     true, false, '0x01', 'v3_1', 'single', 'transfer_from',
     '0x01', '0x01', '0x01', '0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
     '0xdddddddddddddddddddddddddddddddddddddddd', 1, 0,
     0, 1, 0, 1, '{}', '{}', false, false, NULL),
    ('old-trade', 'ethereum', 1, now() - interval '2 hours', '0x06', 0, 0,
     true, true, '0x01', 'v3_1', 'single', 'transfer_from',
     '0x01', '0x01', '0x01', '0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
     '0xdddddddddddddddddddddddddddddddddddddddd', 1, 0,
     0, 1, 0, 1, '{}', '{}', false, false, NULL),
    ('stale-price', 'base', 1, now(), '0x07', 0, 0,
     true, true, '0x01', 'v3_1', 'single', 'transfer_from',
     '0x01', '0x01', '0x01', '0xcccccccccccccccccccccccccccccccccccccccc',
     '0xdddddddddddddddddddddddddddddddddddddddd', 1000000, 0,
     0, 1, 0, 1, '{}', '{}', false, false, NULL);
